server:
  port: 8101

spring:
  application:
    name: Royce-Auth
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://admin:admin@localhost:8001/register/eureka/
